#version 450 core

layout(binding=0) buffer InputA { vec4 x[]; } inputA;
layout(binding=1) buffer InputB { vec4 x[]; } inputB;
layout(binding=2) buffer Output { vec4 x[]; } outputO;

const uint TILE_M = 8;
const uint TILE_N = 64;
const uint TILE_K = 4;
const uint WG_X = 16;
const uint WG_Y = 1;

layout(local_size_x = WG_X, local_size_y = WG_Y, local_size_z = 1) in;

// 特化常量，在 vkCreateComputePipelines 中通过 pSpecializationInfo 指定。
// constant_id 对应偏移量，以0为首地址往后按数据类型内存占用量进行偏移
layout(constant_id = 0) const uint M = 1;
layout(constant_id = 1) const uint N = 1;
layout(constant_id = 2) const float K = 1;

/*
    const uvec3 gl_WorkGroupSize: contains the size of the workgroup operated on by a compute shader
    in uvec3 gl_NumWorkGroups: contains the number of workgroups that have been dispatched to a compute shader

    in uvec3 gl_WorkGroupID: contains the index of the workgroup currently being operated on by a compute shader
    in uvec3 gl_LocalInvocationID: (线程局部下标) contains the index of work item currently being operated on by a compute shader

    in uvec3 gl_GlobalInvocationID: (线程全局下标) contains the global index of work item currently being operated on by a compute shader
    in uint gl_LocalInvocationIndex: (线程局部一维线性下标，上面的是三维) contains the local linear index of work item currently being operated on by a compute shader
*/

void main()
{
    uvec3 gSize = gl_WorkGroupSize;
    uvec2 gID = gl_WorkGroupID.xy;
    uvec2 laneId = gl_LocalInvocationID.xy;

    if (gID.x == 0 && gID.y == 0) {
        outputO.x[0] = vec4(M, N, K, 111.f);
        outputO.x[1] = vec4(gSize.x, gSize.y, gSize.z, 123.f);
    }
}
